# Generated by Django 5.0.1 on 2024-01-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('emailTitle', models.CharField(max_length=200)),
                ('emailContent', models.CharField(max_length=1000)),
                ('startDate', models.DateTimeField(verbose_name='date started')),
                ('endDate', models.DateTimeField(verbose_name='date ended')),
                ('isActivate', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Signoff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soteam', models.CharField(max_length=50)),
                ('soby', models.CharField(max_length=100)),
                ('sodate', models.DateField(verbose_name='sodate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somgr.project')),
            ],
        ),
    ]
