# Generated by Django 5.0.1 on 2024-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='soteam',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
    ]
