# Generated by Django 5.0.1 on 2024-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somgr', '0002_alter_signoff_soteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='signoff',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='emailContent',
            field=models.CharField(max_length=1000, verbose_name='Email Content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='emailTitle',
            field=models.CharField(max_length=200, verbose_name='Email Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(null=True, verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='project',
            name='isActivate',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='soby',
            field=models.CharField(blank=True, max_length=100, verbose_name='SO By'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='sodate',
            field=models.DateTimeField(null=True, verbose_name='SO Date'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='soteam',
            field=models.CharField(max_length=50, verbose_name='SO Team'),
        ),
    ]
