# Generated by Django 5.0.1 on 2024-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somgr', '0003_signoff_note_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdBy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Created By'),
        ),
    ]
