# Generated by Django 5.0.1 on 2024-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somgr', '0004_project_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createdBy',
            field=models.CharField(max_length=200, verbose_name='Created By'),
        ),
    ]
