# Generated by Django 5.0.1 on 2024-01-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somgr', '0005_alter_project_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='sodate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SO Date'),
        ),
    ]
