# Generated by Django 5.0.1 on 2024-01-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somgr', '0006_alter_signoff_sodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Ended'),
        ),
    ]
